[package]
name = "musicbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.8.0"
ctrlc = "3.2.3"
crossbeam = "0.8.2"
